name: toa_flutter
description: An app for accessing data about the FIRST Tech Challenge.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 2.0.1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  http: '>=0.11.3+12'
  shared_preferences: ^0.4.3
  flutter_sticky_header: ^0.4.0
  intl: ^0.15.7
  cupertino_icons: ^0.1.2
  material_design_icons_flutter: ^3.0.3392
  url_launcher: ^4.0.2
  add_2_calendar: ^1.0.2
  dynamic_theme: ^1.0.0
  rounded_modal: ^1.0.0
  rect_getter: ^0.0.1

  # Firebase
  firebase_core: ^0.4.0+6
  firebase_auth: ^0.11.1+7
  firebase_database: ^3.0.3
  firebase_storage: ^3.0.2
  firebase_analytics: ^3.0.3

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  # Material Icons Font.
  uses-material-design: true
  assets:
    - assets/images/event.jpg
    - assets/images/loading.gif
    - assets/lang/en.json
    - assets/lang/he.json
  fonts:
    - family: TOA Icons
      fonts:
        - asset: assets/fonts/TOAIcons.ttf

    - family: GoogleSans
      fonts:
        - asset: assets/fonts/GoogleSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/GoogleSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/GoogleSans-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/GoogleSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/GoogleSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/GoogleSans-Regular.ttf
          weight: 400